baseUrl = "http://golangshow.com/"
languageCode = "ru-RU"
title = "Подкаст GolangShow"
theme = "golangshow"
paginate = 5
disqusShortname = "golangshow"
copyright = "All rights reserved - 2015"

[params]
  description = "Сайт русскоязычного подкаста о Go"
  # cover = "images/cover.png"
  logo = "images/logo.png"
  # googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..." 
  # githubName = "GolangShow"
  # twitterName = "vjeantet"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true

[[menu.main]]
  name = "Главная"
  weight = -120
  identifier = "main"
  url = "/"

#[[menu.main]]
#  name = "О подкасте"
#  weight = -110
#  identifier = "about"
#  url = "/about"

[[menu.main]]
  name = "Онлайн вещание"
  weight = -100
  identifier = "online"
  url = "/online"